"""Bounding-box normalisation, bit-exact with the CSS version generated by build.py.

The drawing is cropped to its bounding box, padded to a square (centred), and
nearest-neighbour resampled back to 8x8, so the network sees every digit at the
same size and position no matter where it was drawn.

CSS has no floor(), but a registered <integer> property rounds to the nearest
integer. For the values used here (multiples of 1/16), floor(x) == round(x - 0.49),
so this file uses exactly that formula to stay identical to the browser.
"""
import numpy as np

GRID = 8


def css_floor(x):
    """floor(x), computed the way the CSS does it: round-to-nearest of x - 0.49."""
    return np.floor(np.asarray(x) - 0.49 + 0.5).astype(int)


def extent(lines_with_ink):
    """(first inked line, number of lines spanned) along one axis."""
    empty = 1 - lines_with_ink
    leading = int(np.cumprod(empty).sum())
    trailing = int(np.cumprod(empty[::-1]).sum())

    return leading, GRID - leading - trailing


def sample_positions(start, size, side):
    """Which source line each of the 8 output lines reads from."""
    origin = start - css_floor((side - size) / 2)
    steps = css_floor((np.arange(GRID) + 0.5) * side / GRID)

    return origin + steps


def normalize_one(grid):
    top, height = extent(grid.max(axis=1))
    left, width = extent(grid.max(axis=0))
    side = max(height, width)

    rows = sample_positions(top, height, side)
    cols = sample_positions(left, width, side)

    out = np.zeros_like(grid)
    for r, src_r in enumerate(rows):
        for c, src_c in enumerate(cols):
            if 0 <= src_r < GRID and 0 <= src_c < GRID:
                out[r, c] = grid[src_r, src_c]

    return out


def normalize(X):
    """Normalise a batch of flattened 8x8 binary drawings."""
    grids = X.reshape(-1, GRID, GRID).astype(int)
    out = np.array([normalize_one(g) for g in grids])

    return out.reshape(len(X), GRID * GRID)
